apiVersion: v1
kind: ConfigMap
metadata:
  name: secureflow-config
  namespace: secureflow
data:
  # No secrets here — all secrets moved to Vault
  AUTH_DB_HOST: "auth-db"
  TX_DB_HOST: "transaction-db"

