apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: secureflow
spec:
  replicas: 1
  selector:
    matchLabels:
      svc: frontend
  template:
    metadata:
      labels:
        svc: frontend
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "frontend-role"
        vault.hashicorp.com/agent-inject-secret-frontend: "secureflow/frontend"
        vault.hashicorp.com/agent-inject-template-frontend: |
          {{- with secret "secureflow/frontend" -}}
          export SESSION_SECRET="{{ .Data.data.SESSION_SECRET }}"
          export AUTH_SERVICE_URL="{{ .Data.data.AUTH_SERVICE_URL }}"
          export TRANSACTION_SERVICE_URL="{{ .Data.data.TRANSACTION_SERVICE_URL }}"
          {{- end }}
    spec:
      serviceAccountName: frontend-sa
      containers:
        - name: frontend
          image: jkairuthi/frontend:py312
          imagePullPolicy: Always
          ports:
            - containerPort: 5000

          # -----------------------------
          # HEALTH PROBES (NEW)
          # -----------------------------
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10

          envFrom:
            - configMapRef:
                name: secureflow-config

          securityContext:
            privileged: true
            allowPrivilegeEscalation: true
            runAsUser: 0
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: secureflow
spec:
  type: NodePort
  selector:
    svc: frontend
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30080
