#Create Service Accounts for each microservice
apiVersion: v1
kind: ServiceAccount
metadata:
  name: auth-sa
  namespace: secureflow
  labels:
    app: auth-service
    team: secureflow
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend-sa
  namespace: secureflow
  labels:
    app: frontend
    team: secureflow
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: transaction-sa
  namespace: secureflow
  labels:
    app: transaction-service
    team: secureflow
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: auth-db-sa
  namespace: secureflow
  labels:
    app: auth-db
    team: secureflow
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: transaction-db-sa
  namespace: secureflow
  labels:
    app: transaction-db
    team: secureflow




