apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-service
  namespace: secureflow
spec:
  replicas: 1
  selector:
    matchLabels:
      svc: transaction-service
  template:
    metadata:
      labels:
        svc: transaction-service
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "transaction-role"

        # Inject TX_DB_PASSWORD from Vault
        vault.hashicorp.com/agent-inject-secret-TX_DB_PASSWORD: "secureflow/data/transaction"
        vault.hashicorp.com/agent-inject-template-TX_DB_PASSWORD: |
          {{- with secret "secureflow/data/transaction" -}}
          export TX_DB_PASSWORD="{{ .Data.data.TX_DB_PASSWORD }}"
          {{- end }}

    spec:
      serviceAccountName: transaction-sa
      containers:
        - name: transaction-service
          image: jkairuthi/transaction-service:py312
          imagePullPolicy: Always
          ports:
            - containerPort: 5002

          # ----------------------------------------
          # HEALTH PROBES
          # ----------------------------------------
          livenessProbe:
            httpGet:
              path: /health
              port: 5002
            initialDelaySeconds: 5
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /health
              port: 5002
            initialDelaySeconds: 5
            periodSeconds: 10

          # ----------------------------------------
          # CONFIGMAP (non‑secret values)
          # ----------------------------------------
          envFrom:
            - configMapRef:
                name: secureflow-config

          # ----------------------------------------
          # ENV VARS (non‑secret)
          # ----------------------------------------
          env:
            - name: DB_HOST
              value: transaction-db
            - name: DB_NAME
              value: transactiondb
            - name: DB_USER
              value: txuser

            # Secret injected by Vault
            - name: TX_DB_PASSWORD
              value: ""

            # Not a secret — safe to hardcode
            - name: AUTH_SERVICE_URL
              value: "http://auth-service:5001"

          # ----------------------------------------
          # SECURITY CONTEXT (intentionally vulnerable)
          # ----------------------------------------
          securityContext:
            privileged: true
            allowPrivilegeEscalation: true
            runAsUser: 0

---
apiVersion: v1
kind: Service
metadata:
  name: transaction-service
  namespace: secureflow
spec:
  selector:
    svc: transaction-service
  ports:
    - port: 5002
      targetPort: 5002

