apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-service
  namespace: secureflow
spec:
  replicas: 1
  selector:
    matchLabels:
      svc: transaction-service
  template:
    metadata:
      labels:
        svc: transaction-service
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "transaction-role"
        vault.hashicorp.com/agent-inject-secret-transaction: "secureflow/transaction-service"
        vault.hashicorp.com/agent-inject-template-transaction: |
          {{- with secret "secureflow/transaction-service" -}}
          export DB_PASSWORD="{{ .Data.data.DB_PASSWORD }}"
          export AUTH_SERVICE_URL="{{ .Data.data.AUTH_SERVICE_URL }}"
          {{- end }}
    spec:
      serviceAccountName: transaction-sa
      containers:
        - name: transaction-service
          image: jkairuthi/transaction-service:py312
          imagePullPolicy: Always
          ports:
            - containerPort: 5002

          # ----------------------------------------
          # HEALTH PROBES (NEW)
          # ----------------------------------------
          livenessProbe:
            httpGet:
              path: /health
              port: 5002
            initialDelaySeconds: 5
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /health
              port: 5002
            initialDelaySeconds: 5
            periodSeconds: 10

          envFrom:
            - configMapRef:
                name: secureflow-config

          env:
            - name: DB_HOST
              value: transaction-db
            - name: DB_NAME
              value: transactiondb
            - name: DB_USER
              value: txuser
            - name: DB_PASSWORD
              value: ""
            - name: AUTH_SERVICE_URL
              value: ""

          securityContext:
            privileged: true
            allowPrivilegeEscalation: true
            runAsUser: 0
---
apiVersion: v1
kind: Service
metadata:
  name: transaction-service
  namespace: secureflow
spec:
  selector:
    svc: transaction-service
  ports:
    - port: 5002
      targetPort: 5002

