#Create Service Accounts for each microservice
apiVersion: v1
kind: ServiceAccount
metadata:
  name: auth-sa
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: transaction-sa
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend-sa
  namespace: default
